# Generated by Django 5.2.3 on 2025-06-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeeprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(max_length=20),
        ),
    ]
